version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            sudo apt-get install libgtest-dev -y
            sudo apt-get install cmake -y
      - run:
          name: Configure cmake
          command: |
            cd /usr/src/gtest
            sudo cmake CMakeLists.txt
            sudo make
            ls -la
            cd
      - run:
          name: Copy files configuration
          command: |
            sudo cp /usr/src/gtest/libgtest.a /usr/lib
            sudo cp /usr/src/gtest/libgtest_main.a /usr/lib
      - run:
          name: Build
          command: |
            cmake SuckerPunch/SuckerPunch/test/CMakeLists.txt
            make SuckerPunch/SuckerPunch/test/
      - run:
          name: Test
          command: |
            ./runTests
